name: Ping Sitemap to Search Engines

on:
  workflow_run:
    workflows: ["Deploy Documentation"]
    types:
      - completed
  workflow_dispatch: # Allow manual trigger

jobs:
  ping-sitemap:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Wait for GitHub Pages deployment
        run: sleep 60 # Give GitHub Pages time to update
        
      - name: Ping Google
        run: |
          curl -s "https://www.google.com/ping?sitemap=https://vicentereig.github.io/dspy.rb/sitemap.xml"
          echo "✅ Pinged Google"
      
      - name: Ping Bing
        run: |
          curl -s "https://www.bing.com/ping?sitemap=https://vicentereig.github.io/dspy.rb/sitemap.xml"
          echo "✅ Pinged Bing"